### PR TITLE
Update format for grimoirelab v1

### PR DESCRIPTION
**Pull request by canasdiaz**
Update the format of the grimoirelab v1 affiliation format file according to what the Bitergians have discussed internally.

### CODE REVIEW

**Comment by jsmanrique** [comment]
AFAIK, according to @sduenas "Periods for companies should not overlap" is not 100% true. Sorting Hat support it, but gelk enrichment doesn't take it into account. Would it be a issue in gelk?

**Comment by canasdiaz** [comment]
@jsmanrique I don't understand your point buddy. How is that related to the changes I proposed?

In any case, in terms of affiliation the format supports what the Sorting Hat format supports.This file is going to deal with Sorting Hat databases and gelk is the one that has to deal with the database.

**Comment by jsmanrique** [comment]
@sanacl you are saying:
```
Periods for companies should not overlap
```

What's the point with that? Why do we have that _restriction_?

**Comment by jgbarah** [comment]
> @sanacl you are saying:
>
>> Periods for companies should not overlap
>
> What's the point with that? Why do we have that restriction?

I know that one! Because right now, in the enrichment process, if we have a commit during the overlapping period, we really don't know to which company to assign the commit. Usually, it is done at random, which renders bad results (because of the underlying assumption now that enrichment does, that a person is affiliated to only one organization at any given moment).

I know we're in the process of discussing with Mozilla about adding support for multiple organizations, but for now, that's not supported, and this format is for now...

**Comment by jgbarah** [comment]
That's ok with me, @sanacl !!

**Comment by jsmanrique** [comment]
Ok, that's ok with me

**Comment by canasdiaz** [comment]
Thanks for the quick response guys! :+1:

**Pull request merged**
